//Q1)...
document.getElementById("mainTitle").innerHTML = "DOM Manipulation Quiz";
//Q2)...
document.getElementsByTagName("h2")[0].innerHTML = "Modified by TagName";
//Q3)...
document.getElementsByClassName("description")[1].innerHTML =
  "Found by ClassName";
//Q4)...
document.getElementsByClassName("external-link")[0].href =
  "https://auk.edu.krd/";
document.getElementsByClassName("external-link")[1].href =
  "https://auk.edu.krd/10th-anniversary/";
//Q5)...
document.querySelector("#introSection p").innerHTML =
  "Selected by CSS Selector";
//Q6)...
document.forms["contactForm"]["fullName"].placeholder =
  "Enter your full name here";
document.forms["contactForm"]["email"].placeholder = "Enter your email here";
document.forms["contactForm"]["message"].placeholder =
  "Type your message here..";
//Q7)...
document.getElementById("footerText").innerHTML = "This is new footer text";
//Q8)...
document.getElementById("mainImage").src = "img4.png";
//Q9)...
document.getElementById("submitButton").style.backgroundColor = "#00cc66";
